import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { Download, Edit3, Loader2 } from 'lucide-react'
import api from '../../services/api'
const money = value => `₹${Number(value || 0).toLocaleString('en-IN', { minimumFractionDigits: 2 })}`
export default function InvoiceDetail({ admin = false }) {
  const { id } = useParams(), [invoice, setInvoice] = useState(null), [error, setError] = useState('')
  useEffect(() => { api.get(`/invoices/${id}`).then(r => setInvoice(r.data)).catch(e => setError(e.response?.data?.error || 'Unable to load invoice')) }, [id])
  const download = async () => { const r = await api.get(`/invoices/${id}/pdf`, { responseType: 'blob' }); const url = URL.createObjectURL(r.data); const a = document.createElement('a'); a.href = url; a.download = `${invoice.invoiceNumber}.pdf`; a.click(); URL.revokeObjectURL(url) }
  if (error) return <div className="p-6 bg-red-50 text-red-700 rounded-lg">{error}</div>
  if (!invoice) return <div className="flex justify-center p-12"><Loader2 className="animate-spin"/></div>
  return <div className="max-w-5xl"><div className="flex flex-wrap justify-between gap-3 mb-6"><div><p className="text-sm text-sky-600 font-mono">{invoice.invoiceNumber}</p><h1 className="text-2xl font-bold">Invoice</h1></div><div className="flex gap-2"><button onClick={download} className="inline-flex items-center gap-2 px-4 py-2 bg-sky-600 text-white rounded-lg"><Download size={16}/> Download PDF</button>{admin && <Link to={`/admin/invoices/${id}/edit`} className="inline-flex items-center gap-2 px-4 py-2 border rounded-lg"><Edit3 size={16}/> Edit</Link>}</div></div><div className="bg-white border rounded-xl p-6"><div className="grid md:grid-cols-2 gap-6 border-b pb-6"><div><h2 className="text-lg font-bold text-sky-700">{invoice.companyName || 'TravelVista'}</h2><p className="text-sm text-navy-500 whitespace-pre-line">{invoice.companyAddress}</p><p className="text-sm mt-4"><b>Bill to:</b><br/>{invoice.customerName}<br/>{invoice.customerEmail}<br/>{invoice.customerPhone}<br/>{invoice.customerAddress}</p></div><div className="md:text-right text-sm"><p>Date: {invoice.invoiceDate || '—'}</p><p>Due: {invoice.dueDate || '—'}</p><p>Booking: {invoice.booking?.bookingRef || '—'}</p><p className="mt-2">Status: <b>{invoice.status}</b></p></div></div><div className="overflow-x-auto mt-6"><table className="w-full"><thead><tr className="border-b text-left text-xs uppercase text-navy-500"><th className="py-3">Description</th><th className="py-3">Qty</th><th className="py-3">Rate</th><th className="py-3">Tax</th><th className="py-3 text-right">Amount</th></tr></thead><tbody>{(invoice.items || []).map(item => <tr key={item.id || item.serialNo} className="border-b"><td className="py-3">{item.description}</td><td>{item.quantity}</td><td>{money(item.rate)}</td><td>{money(item.totalTax)}</td><td className="text-right">{money(item.lineTotal)}</td></tr>)}</tbody></table></div><div className="ml-auto mt-6 max-w-xs space-y-2 text-sm"><p className="flex justify-between"><span>Subtotal</span><b>{money(invoice.baseAmount)}</b></p><p className="flex justify-between"><span>CGST</span><span>{money(invoice.cgstAmount)}</span></p><p className="flex justify-between"><span>SGST</span><span>{money(invoice.sgstAmount)}</span></p><p className="flex justify-between"><span>IGST</span><span>{money(invoice.igstAmount)}</span></p><p className="flex justify-between border-t pt-2 text-lg"><b>Grand Total</b><b className="text-sky-700">{money(invoice.grandTotal)}</b></p></div><div className="mt-6 text-sm text-navy-500"><p>Payment: {invoice.paymentMode || '—'} {invoice.paymentReference ? `(${invoice.paymentReference})` : ''}</p>{invoice.notes && <p className="mt-2 whitespace-pre-line">{invoice.notes}</p>}</div></div></div>
}
