import { useEffect, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { Download, Edit3, Eye, FileText, Mail, Plus, Trash2 } from 'lucide-react'
import api from '../../services/api'

const money = value => `₹${Number(value || 0).toLocaleString('en-IN', { minimumFractionDigits: 2 })}`
const messageOf = error => error.response?.data?.error || error.response?.data?.message || 'Invoice request failed'

export default function AdminInvoices() {
  const [invoices, setInvoices] = useState([]), [stats, setStats] = useState(null)
  const [loading, setLoading] = useState(true), [error, setError] = useState(''), [sending, setSending] = useState(null)
  const navigate = useNavigate()
  const load = () => { setLoading(true); Promise.all([api.get('/invoices'), api.get('/invoices/stats')]).then(([a, b]) => { setInvoices(a.data); setStats(b.data) }).catch(e => setError(messageOf(e))).finally(() => setLoading(false)) }
  useEffect(load, [])
  const download = async id => { const response = await api.get(`/invoices/${id}/pdf`, { responseType: 'blob' }); const url = URL.createObjectURL(response.data); const a = document.createElement('a'); a.href = url; a.download = `invoice-${id}.pdf`; a.click(); URL.revokeObjectURL(url) }
  const send = async invoice => { if (!window.confirm(`Send ${invoice.invoiceNumber} to ${invoice.customerEmail}?`)) return; setSending(invoice.id); try { await api.post(`/invoices/${invoice.id}/send`, { sendVia: 'email', recipientEmail: invoice.customerEmail }); load(); alert('Invoice email accepted for sending.') } catch (e) { alert(messageOf(e)) } finally { setSending(null) } }
  const remove = async invoice => { if (!window.confirm(`Delete invoice ${invoice.invoiceNumber}?`)) return; try { await api.delete(`/invoices/${invoice.id}`); setInvoices(x => x.filter(i => i.id !== invoice.id)) } catch (e) { alert(messageOf(e)) } }
  const updateStatus = async (invoice, status) => { try { const response = await api.put(`/invoices/${invoice.id}/status`, { status }); setInvoices(x => x.map(i => i.id === invoice.id ? response.data : i)) } catch (e) { alert(messageOf(e)) } }
  return <div>
    <div className="flex flex-wrap items-center justify-between gap-4 mb-6"><div><h1 className="text-2xl font-bold text-navy-900">Invoices</h1><p className="text-sm text-navy-500">Authoritative totals from the invoice service</p></div><Link to="/admin/invoices/new" className="inline-flex items-center gap-2 px-4 py-2 bg-sky-600 text-white rounded-lg text-sm font-medium"><Plus size={16}/> Create Invoice</Link></div>
    {stats && <div className="grid grid-cols-2 lg:grid-cols-5 gap-3 mb-6">{[['Total', stats.totalInvoices], ['Paid', stats.paidCount], ['Pending', stats.pendingCount], ['Revenue', money(stats.totalRevenue)], ['Tax', money(stats.totalTaxCollected)]].map(([label, value]) => <div key={label} className="bg-white rounded-xl border p-4"><p className="text-xs uppercase text-navy-400">{label}</p><p className="text-xl font-bold text-navy-900 mt-1">{value}</p></div>)}</div>}
    {error && <div className="p-4 mb-4 rounded-lg bg-red-50 text-red-700">{error}</div>}
    <div className="bg-white rounded-xl border overflow-x-auto">{loading ? <div className="p-12 text-center text-navy-500">Loading invoices...</div> : invoices.length === 0 ? <div className="p-12 text-center text-navy-500"><FileText className="mx-auto mb-2"/>No invoices found.</div> : <table className="w-full min-w-[950px]"><thead><tr className="bg-gray-50 border-b text-xs uppercase text-navy-500"><th className="text-left p-4">Invoice</th><th className="text-left p-4">Customer</th><th className="text-left p-4">Date</th><th className="text-right p-4">Total</th><th className="text-left p-4">Status</th><th className="text-right p-4">Actions</th></tr></thead><tbody>{invoices.map(i => <tr key={i.id} className="border-b last:border-0"><td className="p-4 font-mono text-sm">{i.invoiceNumber}</td><td className="p-4"><p className="font-medium">{i.customerName}</p><p className="text-xs text-navy-500">{i.customerEmail}</p></td><td className="p-4 text-sm">{i.invoiceDate || '—'}</td><td className="p-4 text-right font-semibold">{money(i.grandTotal)}</td><td className="p-4"><select value={i.status || 'draft'} onChange={e => updateStatus(i, e.target.value)} className="px-2 py-1 rounded-full bg-slate-100 text-xs border-0"><option value="draft">draft</option><option value="sent">sent</option><option value="paid">paid</option><option value="unpaid">unpaid</option><option value="cancelled">cancelled</option></select></td><td className="p-4"><div className="flex justify-end gap-1"><button title="View" onClick={() => navigate(`/admin/invoices/${i.id}`)} className="p-2 text-sky-600"><Eye size={16}/></button><button title="Edit" onClick={() => navigate(`/admin/invoices/${i.id}/edit`)} className="p-2 text-sky-600"><Edit3 size={16}/></button><button title="Download" onClick={() => download(i.id)} className="p-2 text-slate-600"><Download size={16}/></button><button title="Send email" disabled={sending === i.id} onClick={() => send(i)} className="p-2 text-slate-600"><Mail size={16}/></button><button title="Delete" onClick={() => remove(i)} className="p-2 text-red-600"><Trash2 size={16}/></button></div></td></tr>)}</tbody></table>}</div>
  </div>
}
